export default {
  namespaced: true,
  state() {
    return {
      products: [
        {
          id: 0,
          image: require("../../assets/img/allef-vinicius-sGX-7xDnuE0-unsplash.jpg"),
          title: "ساعت وییب",
          price: 200000,
          description: "این ساعت از بهترین ساعت ها ی حال حاضر است",
          category: "watch",
          category_name: "ساعت",
        },
        {
          id: 1,
          image: require("../../assets/img/andres-vera-CmmYT6Mm948-unsplash.jpg"),
          title: "گردنبد یاقوت ابی",
          price: 100000,
          description: "این گردنبد از بهترین ساعت ها ی حال حاضر است",
          category: "necklaces",
          category_name: "گردنبد",
        },
        {
          id: 2,
          image: require("../../assets/img/bruno-van-der-kraan-VRERJ5Mjp4c-unsplash.jpg"),
          title: "ساعت کلاسیک روزلیس",
          price: 300000,
          description: "این ساعت از بهترین ساعت ها ی حال حاضر است",
          category: "watch",
          category_name: "ساعت",
        },
        {
          id: 3,
          image: require("../../assets/img/vitae-london-331tAGMqa8Y-unsplash.jpg"),
          title: "گردنبد نقره",
          price: 100000,
          description: "این گردنبد از بهترین ساعت ها ی حال حاضر است",
          category: "necklaces",
          category_name: "گردنبد",
        },
        {
          id: 4,
          image: require("../../assets/img/invalid-account-u1Hv_erOQH0-unsplash.jpg"),
          title: "انگشتر الماس",
          price: 100000,
          description: "این انگشتر از بهترین ساعت ها ی حال حاضر است",
          category: "ring",
          category_name: "انگشتر",
        },
        {
          id: 5,
          image: require("../../assets/img/high_res-51.jpg"),
          title: "گرنبد نمونه سال",
          price: 100000,
          description: "این گرنبد از بهترین ساعت ها ی حال حاضر است",
          category: "necklaces",
          category_name: "گرنبد",
        },
        {
          id: 6,
          image: require("../../assets/img/jasmin-chew-UBeNYvk6ED0-unsplash.jpg"),
          title: "گوشواره یاقوتی",
          price: 100000,
          description: "این گوشواره از بهترین ساعت ها ی حال حاضر است",
          category: "Earrings",
          category_name: "گوشواره",
        },
        {
          id: 7,
          image: require("../../assets/img/jeremy-beadle-qnU-UR0o5X8-unsplash.jpg"),
          title: "ساعت لوکس",
          price: 900000,
          description: "این ساعت از بهترین ساعت ها ی حال حاضر است",
          category: "watch",
          category_name: "ساعت",
        },
        {
          id: 8,
          image: require("../../assets/img/kylefromthenorth-Dcw_Z5o7ovY-unsplash (1).jpg"),
          title: "انگشتر الماس",
          price: 100000,
          description: "این انگشتر از بهترین ساعت ها ی حال حاضر است",
          category: "ring",
          category_name: "انگشتر",
        },
        {
          id: 9,
          image: require("../../assets/img/lloyd-dirks-0vsk2_9dkqo-unsplash (1).jpg"),
          title: "ساعت هوشمند",
          price: 500000,
          description: "این ساعت از بهترین ساعت ها ی حال حاضر است",
          category: "watch",
          category_name: "ساعت",
        },
        {
          id: 10,
          image: require("../../assets/img/pat-taylor-12V36G17IbQ-unsplash.jpg"),
          title: "ساعت کلاسیک",
          price: 500000,
          description: "این ساعت از بهترین ساعت ها ی حال حاضر است",
          category: "watch",
          category_name: "ساعت",
        },
      ],
    };
  },

  getters: {
    products(state) {
      return state.products;
    },
  },
};
